### ISSUE TITLE
Invoke /send using postman

### ISSUE THREAD

**Issue by zohaib85** [MartijnDwars/spring-boot-web-push#1]
Martin, I'm trying to invoke /send controller using postman but its failing by saying could not find subscription id. Can you please share sample json payload? I want to expose that endpoint externally and invoke from android.
Also in push.js you have /profile/subscription endpoint which could not understand from where it is coming from and whats its purpose

thanks

**Comment by martijndwars** [comment]
> Martin, I'm trying to invoke /send controller using postman but its failing by saying could not find subscription id. Can you please share sample json payload? I want to expose that endpoint externally and invoke from android.

The `/send` endpoint was not really designed to be used as a REST endpoint. If you open http://localhost:8080/ and hit the "Send notification" button, you can see the request that's being sent in Chrome's DevTools. For example:

![Chrome DevTools request](https://user-images.githubusercontent.com/426811/46256054-91d36b80-c4a5-11e8-888c-ca5e98195ab2.png)

Note that the example sends a POST request of type "form-data" with appropriate body, i.e. not a raw POST request with JSON body. You can adapt this to your own needs, of course.

> Also in push.js you have /profile/subscription endpoint which could not understand from where it is coming from and whats its purpose

You are referring to [line 79-91](https://github.com/MartijnDwars/spring-boot-web-push/blob/d4c5490c913a4f4837c278ae6bb375224caf5382/src/main/resources/static/push.js#L79-L91). In this demo these lines serve no purpose. In a practical application you probably want to save the subscription in your database and use it in the future to send a notification. One way to do this is by making a POST request with the subscription to some endpoint on your server (such as /profile/subscription in this example). These lines demonstrate how to do  that.

**Comment by martijndwars** [comment]
I'm closing the issue as it does not involve a problem with the code (but rather how to use the code), but feel free to reply if you have any other problems.

**Comment by zohaib85** [comment]
Thanks MartijnDwars, for some reason my chrome devtools was not showing the send requests. It worked for me now. For /profile/subscription where does it endpoint resides?

**Comment by martijndwars** [comment]
> For /profile/subscription where does it endpoint resides?

You have to create this endpoint yourself. The endpoint would have to persist the subscription in your database. Since this is different for everybody, this demo does not implement this endpoint.
