### ISSUE TITLE
New key pairs won't work

### ISSUE THREAD

**Issue by zohaib85** [MartijnDwars/spring-boot-web-push#2]
Hi Martin,
I tried using new keys generated from https://web-push-codelab.glitch.me/, replaced public key in push.js file and in java controller file. Did I miss anything?
I get 403 back from server, any suggestions?

Thanks

**Comment by martijndwars** [comment]
> I get 403 back from server, any suggestions?

The 403 occurs when you press the "Send a notification ..." button on http://localhost:8080/ (i.e. when you send the subscription to the webserver)? Or when the webserver sends the push notification to the browser vendor (Google, Mozilla, ...)?

**Comment by zohaib85** [comment]
I get 403 when webserver sends the push notification to the browser (chrome in my case).

**Comment by zohaib85** [comment]
Sorry never mind, it browser cookies were blocking 👍 
Thank you.
